#!/usr/bin/env ruby
# vim: set filetype=ruby

# TODO: jslint
#       setup linux to install dependencies
#       configure https://github.com/Shougo/unite.vim
#       configure https://github.com/bling/vim-airline

require 'rubygems'
require 'bundler/setup'
require "thor"

class DotfilesCLI < Thor
  include Thor::Actions

  desc "install", "Creates symlinks in home directory"
  def install
    # install dependencies (mac only, TODO: unix)
    Bundler.with_clean_env do
      case RUBY_PLATFORM
      when /linux/              
      when /darwin/
        `brew install zsh cscope ctags bazaar git git-extras hub lua luajit mercurial tmux the_silver_searcher zsh-lovers rbenv ruby-build rbenv-binstubs rbenv-gem-rehash nodejs cmake autoconf ack automake openssl ssh-copy-id tmate watch`
        `brew install macvim --with-cscope --with-lua --with-luajit --with-python --override-system-vim --HEAD`
        `brew linkapps macvim`
      end
    end

    # setup Go plugins for vim
    create_link "#{__dir__}/.vim/local_bundle/go", "#{ENV['GOROOT']}/misc/vim"

    # compile gocode
    Bundler.with_clean_env do
      `cd #{__dir__}/vendor/deps/gocode && go build`
    end

    create_link "/usr/local/gocode", "vendor/deps/gocode/gocode"
    create_link "#{__dir__}/.vim/local_bundle/gocode", "#{__dir__}/vendor/deps/gocode/vim"

    # install zsh / zprezto
    create_link "~/.zprezto", File.join(__dir__, "vendor/deps/prezto")
    Dir['.z*'].each {|p| create_link "~/#{p}", File.join(__dir__, p) }

    # vim symlinks
    create_link "~/.vim", File.join(__dir__, ".vim")
    create_link "~/.vimrc", File.join(__dir__, ".vim/vimrc")
    create_link "~/.gvimrc", File.join(__dir__, ".vim/gvimrc")

    # git symlinks
    create_link "~/.gitignore", File.join(__dir__, ".gitignore")
    create_link "~/.gitconfig", File.join(__dir__, ".gitconfig")

    # misc symlinks
    create_link "~/.agignore", File.join(__dir__, ".agignore")
    create_link "~/.ctags", File.join(__dir__, ".ctags")
    create_link "~/.tmux.conf", File.join(__dir__, ".tmux.conf")
    create_link "~/.gemrc", File.join(__dir__, ".gemrc")
    create_link "~/.rbenv/default-gems", File.join(__dir__, ".rbenv/default-gems")
  end

  desc "uninstall", "Removes symlinks in home directory"
  def uninstall
    say "uninstalling"
    `rm ~/.zprezto`
    `rm ~/.zpreztorc`
    `rm ~/.zshrc`
    `rm ~/.zlogin`
    `rm ~/.zlogout`
    `rm ~/.zprofile`
    `rm -rf ~/.vim`
    `rm ~/.vimrc`
    `rm ~/.gvimrc`
    `rm ~/.gitconfig`
    `rm ~/.gitignore`
    `rm ~/.aginore`
    `rm ~/.ctags`
    `rm ~/.tmux.conf`
    `rm ~/.gemrc`
    `rm -rf ~/.rbenv`
  end

  desc "update", "Updates dependencies"
  def update
    Bundler.with_clean_env do
      say "updating gocode"
      `cd vendor/deps/gocode && git pull origin master`
      create_link "/usr/local/gocode", "vendor/deps/gocode/gocode"
      create_link "#{__dir__}/.vim/local_bundle/gocode", "#{__dir__}/vendor/deps/gocode/vim"

      say "updating neobundle"
      `cd .vim/bundle/neobundle.vim && git pull origin master`

      say "updating prezto"
      `cd vendor/deps/prezto && git pull origin master`

      say "updating base16-iterm2"
      `cd vendor/deps/base16-iterm2.git && git pull origin master`
    end
  end
end

DotfilesCLI.start(ARGV)
