[delta]
navigate = true
side-by-side = true
features = "catppuccin-mocha"

[delta "catppuccin-mocha"]
blame-palette = "#1e1e2e #181825 #11111b #313244 #45475a"
commit-decoration-style = "#6c7086" bold box ul
dark = true
file-decoration-style = "#6c7086"
file-style = "#cdd6f4"
hunk-header-decoration-style = "#6c7086" box ul
hunk-header-file-style = bold
hunk-header-line-number-style = bold "#a6adc8"
hunk-header-style = file line-number syntax
line-numbers = true
line-numbers-left-style = "#6c7086"
line-numbers-minus-style = bold "#f38ba8"
line-numbers-plus-style = bold "#94d4c8"
line-numbers-right-style = "#6c7086"
line-numbers-zero-style = "#6c7086"
minus-emph-style = bold syntax "#5a2338"
minus-style = syntax "#3d1e28"
plus-emph-style = bold syntax "#1a5a45"
plus-style = syntax "#1e3d35"
map-styles = \
    bold purple => syntax "#5b4e74", \
    bold blue => syntax "#445375", \
    bold cyan => syntax "#446170", \
    bold yellow => syntax "#6b635b"
syntax-theme = "Catppuccin Mocha"

